alfresco:
  image: webcenter/rancher-alfresco:v5.1.0-2
  environment:
    CIFS_ENABLED: "false"
    FTP_ENABLED: "false"
    DB_NAME: alfresco
    DATABASE_NAME: alfresco
    DATABASE_HOST: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_USER: postgres
  labels:
    io.rancher.container.pull_image: always
  tty: true
  links:
  - postgres:db
  stdin_open: true
  ports:
  - 8181:8080/tcp

postgres:
  image: postgres:9.3
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: alfresco
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  labels:
    io.rancher.container.pull_image: always
  tty: true
  stdin_open: true

